# Documentation: https://yamllint.readthedocs.io/en/stable/rules.html
extends: default
rules:
  line-length:
    max: 3000
  document-start:
    present: false
  empty-lines:
    max: 1
  hyphens:
    max-spaces-after: 1
