---
- name: Prepare
  hosts: manager
  gather_facts: true
  tasks:

    - name: "Install dependencies"
      package:
        name:
          - curl
          - net-tools
        state: latest
      register: wazuh_manager_dependencies_packages_installed
      until: wazuh_manager_dependencies_packages_installed is succeeded

  roles:
    - role: wazuh/ansible-wazuh-manager

- name: Prepare
  hosts: agent
  gather_facts: true
  tasks:

    - name: "Install Python packages for Trusty to solve trust issues"
      package:
        name:
          - python-setuptools
          - python-pip
        state: latest
      register: wazuh_manager_trusty_packages_installed
      until: wazuh_manager_trusty_packages_installed is succeeded
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version | int == 14

    - name: "Install dependencies"
      package:
        name:
          - curl
          - net-tools
        state: latest
      register: wazuh_agent_dependencies_packages_installed
      until: wazuh_agent_dependencies_packages_installed is succeeded
