[tool.pyright]
reportOptionalMemberAccess = "none"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["F", "I", "W", "E", "C90", "N", "D", "UP", "CPY", "YTT", "B", "T20"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "single"

[isort]
lines-after-imports = 2

[tool.ruff.lint.isort]
