export const amazonAWSCard = '[data-test-subj="overviewWelcomeAws"]';
export const gCPCard = '[data-test-subj="overviewWelcomeGcp"]';
export const openSCAPCard = '[data-test-subj="overviewWelcomeOscap"]';
export const cisCatCard = '[data-test-subj="overviewWelcomeCiscat"]';
export const virusTotalCard = '[data-test-subj="overviewWelcomeVirustotal"]';
export const osqueryCard = '[data-test-subj="overviewWelcomeOsquery"]';
export const dockerListenerCard = '[data-test-subj="overviewWelcomeDocker"]';
export const gDPRCard = '[data-test-subj="overviewWelcomeGdpr"]';
export const hIPAACard = '[data-test-subj="overviewWelcomeHipaa"]';
export const tSCCard = '[data-test-subj="overviewWelcomeTsc"]';
export const gitHubCard = '[data-test-subj="overviewWelcomeGithub"]'
