---
- block:

  - name: RedHat/CentOS/Fedora | Add Wazuh indexer repo
    yum_repository:
      file: wazuh
      name: wazuh_repo
      description: Wazuh yum repository
      baseurl: "{{ wazuh_repo.yum }}"
      gpgkey: "{{ wazuh_repo.gpg }}"
      gpgcheck: true
    changed_when: false
    when: not wazuh_custom_packages_installation_indexer_enabled

  - name: Amazon Linux | Install Amazon extras
    block:
      - name: Install Amazon extras
        yum:
          name: amazon-linux-extras
          state: present
          lock_timeout: 180

      - name: Configure vm.max_map_count
        lineinfile:
          line: "vm.max_map_count=262144"
          dest: "/etc/sysctl.conf"
          insertafter: EOF
          create: true
        become: yes

      - name: Update vm.max_map_count
        shell: sysctl -p
        become: yes

    when:
      - ansible_distribution == 'Amazon'

  - name: RedHat/CentOS/Fedora | Install Indexer dependencies
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - unzip

  tags:
  - install

- include_tasks: "install_from_custom_package.yml"
  when: wazuh_custom_packages_installation_indexer_enabled
