export const titleSelector = '[class="euiTitle euiTitle--medium"]';
export const tableSelector = '[class="euiTableRow customRowClass euiTableRow-isClickable"]';
export const dropdownPaginationSelector = '[data-test-subj="tablePaginationPopoverButton"]';
export const listPages = 'nav[class="euiPagination"]';
export const customDecodersButtonSelector = '[class="euiButtonGroup euiButtonGroup--m"]';
export const manageDecodersFilesButtonSelector = ':nth-child(3) > .euiButtonEmpty > .euiButtonContent';
export const editDecoderButtonSelector = '.euiTableCellContent > div > :nth-child(1) > .euiButtonIcon';
export const saveDecoderButtonSelector = '.euiFlexItem--flexGrowZero > .euiButton > .euiButtonContent';
export const messageConfirmSaveSelector = '.euiText > span';
export const buttonRestartSelector = '.euiText--small > .euiFlexGroup > .euiFlexItem--flexGrowZero > .euiButton > .euiButtonContent';