---
- name: Prepare
  hosts: all
  gather_facts: true
  pre_tasks:

    - name: "Install Python packages for Trusty to solve trust issues"
      package:
        name:
          - python-setuptools
          - python-pip
        state: latest
      register: wazuh_manager_trusty_packages_installed
      until: wazuh_manager_trusty_packages_installed is succeeded
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version | int == 14

    - name: "Install dependencies"
      package:
        name:
          - curl
          - net-tools
        state: latest
      register: wazuh_manager_dependencies_packages_installed
      until: wazuh_manager_dependencies_packages_installed is succeeded

    - name: "Install (RedHat) dependencies"
      package:
        name:
          - initscripts
        state: latest
      register: wazuh_manager_dependencies_packages_installed
      until: wazuh_manager_dependencies_packages_installed is succeeded
      when:
        - ansible_os_family == 'RedHat'
