[tool.setuptools]
packages = { find = { where = ["dash_app"] } }

[project]
name = "data_visualization"
version = "0.0.1"
authors = [
  { name="Wazuh", email="hello@wazuh.com" },
]
description = "Data Visualization Module"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "plotly>=5.22.0",
    "dash>=2.17.1",
    "pandas>=2.2.2",
    "dash-mantine-components==0.12.1",
    "Flask-Caching>=2.3.0",
    "dask>=2024.8.0"
]

[project.scripts]
data-visualization-module = "dash_app.app:main"
