---
- name: Converge
  hosts: all
  roles:
    - role: wazuh/ansible-wazuh-manager
      vars:
        wazuh_manager_config:
            cluster:
                disable: 'no'
                name: 'wazuh'
                node_name: 'manager'
                node_type: 'master'
                key: 'ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa'
                port: '1516'
                bind_addr: '0.0.0.0'
                nodes:
                - 'manager_bionic'
                hidden: 'no'
    - { role: wazuh/ansible-filebeat, filebeat_output_elasticsearch_hosts: 'elasticsearch_bionic:9200' }