FROM vpgrp/kitchen:latest

# Update aptitude with new repo
RUN apt-get update

RUN apt-get -y install ssh && apt-get -y update

RUN gem install rails && \
    gem install test-kitchen && \
    gem install kitchen-puppet && \
    gem install kitchen-vagrant && \
    gem install kitchen-docker -v 2.3 && \
    gem install puppet && \
    gem install librarian-puppet

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.5 get-pip.py

RUN pip install pytest && pip install testinfra && pip install paramiko

RUN echo "$(sed -n '/ip6/!p' /etc/hosts)" > /etc/hosts