FROM vpgrp/kitchen:latest

# Update aptitude with new repo
RUN apt-get update

RUN apt-get -y install ssh && apt-get -y update

RUN echo -e "source 'https://rubgems.org'\n\
gem 'test-kitchen'\n\
gem 'kitchen-puppet'\n\
gem 'kitchen-vagrant'\n\
gem 'kitchen-docker', '~> 2.3'\n\
gem 'puppet'\n\
gem 'librarian-puppet'" > Gemfile

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.5 get-pip.py

RUN pip install pytest && pip install testinfra && pip install paramiko

RUN echo "$(sed -n '/ip6/!p' /etc/hosts)" > /etc/hosts