---
- name: Download necessary files
  hosts: all
  gather_facts: false
  tasks:
    - name: Download wazuh-certs-tool.sh
      get_url:
        url: https://packages.wazuh.com/4.7/wazuh-certs-tool.sh
        dest: /home/vagrant/wazuh-certs-tool.sh

    - name: Download config.yml
      get_url:
        url: https://packages.wazuh.com/4.7/config.yml
        dest: /home/vagrant/config.yml

- name: Replace values in config.yml
  hosts: all
  gather_facts: false
  tasks:

#    - name: Execute sed to comment out the dashboard line
#      command: "sed -i '/^  dashboard:/s/^/  #/' /home/vagrant/config.yml"

#    - name: Execute sed to comment out the - dashboard line
#      command: "sed -i '/^    - name: dashboard/s/^/  #/' /home/vagrant/config.yml"

#    - name: Execute sed to comment out the dashboard-node-ip line
#      command: "sed -i '/^      ip: \"<dashboard-node-ip>\"/s/^/  #/' /home/vagrant/config.yml"

    - name: Modify first occurrence of comment in node_type
      command: "sed -i '0,/#  node_type: worker/s/#  node_type:/  node_type:/' /home/vagrant/config.yml"

    - name: Modify first occurrence of comment in IP
      command: "sed -i '0,/#  ip: \"<wazuh-manager-ip>\"/ s/#  ip: \"<wazuh-manager-ip>\"/     ip: \"<wazuh-manager-ip>\"/' /home/vagrant/config.yml"

    - name: Modify comment for wazuh-2
      command: "sed -i 's/^ *#- name: wazuh-2/    - name: wazuh-2/' /home/vagrant/config.yml"

    - name: Modify first occurrence of "<wazuh-manager-ip>"
      command: "sed -i '0,/<wazuh-manager-ip>/s//192.168.57.2/' /home/vagrant/config.yml"

    - name: Modify first occurrence of "<wazuh-manager-ip>"
      command: "sed -i '0,/<wazuh-manager-ip>/s//192.168.57.3/' /home/vagrant/config.yml"

    - name: Modify first occurrence of "<indexer-node-ip>"
      command: "sed -i '0,/<indexer-node-ip>/s//192.168.57.2/' /home/vagrant/config.yml"

    - name: Modify first occurrence of "<dashboard-node-ip>"
      command: "sed -i '0,/<dashboard-node-ip>/s//192.168.57.2/' /home/vagrant/config.yml"


    - name: Execute wazuh-certs-tool.sh -A
      command: bash /home/vagrant/wazuh-certs-tool.sh -A
      become: true

    - name: Package certificates into a tar file
      command: tar -cvf /home/vagrant/wazuh-certificates.tar -C /home/vagrant/wazuh-certificates/ .
      become: true

    - name: Remove the wazuh-certificates directory
      command: rm -rf /home/vagrant/wazuh-certificates
      become: true
