# Copyright (C) 2015, Wazuh Inc.
# Created by Wazuh, Inc. <info@wazuh.com>.
# This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2

- hosts: localhost
  become: true
  tasks:
    - name: Clean test directory
      file:
        path: "{{ working_dir }}"
        state: absent
