- name: Install Wazuh Component
  hosts: all
  gather_facts: false
  become: true
  tasks:
    {% if ansible_os_family == 'RedHat' %}
    - name: Import Wazuh GPG key
      command: rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH

    - name: Add Wazuh repository
      shell: echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages.wazuh.com/4.x/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo

    - name: Install Wazuh Manager
      yum:
        name: wazuh-manager
        state: present
        update_cache: yes
        enablerepo: wazuh

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable Wazuh Manager at boot
      systemd:
        name: wazuh-manager
        enabled: yes

    - name: Start Wazuh Manager
      systemd:
        name: wazuh-manager
        state: started
    {% endif %}

    {% if ansible_os_family == 'Debian' %}
    - name: Install prerequisites
      apt:
        name:
          - gnupg
          - apt-transport-https
        state: present

    - name: Import Wazuh GPG key
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

    - name: Add Wazuh repository
      shell: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list

    - name: Instalar Wazuh Manager
      apt:
        name: wazuh-manager
        state: present
        update_cache: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable Wazuh Manager at boot
      systemd:
        name: wazuh-manager
        enabled: yes

    - name: Start Wazuh Manager
      systemd:
        name: wazuh-manager
        state: started
    {% endif %}

    {% if host == 'master' %}
    - name: Reemplazar NODE_IP con la direcci贸n IP
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<node>NODE_IP</node>'
        replace: '<node>192.168.57.2</node>'
        
    - name: Reemplazar node_name
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<node_name>node01</node_name>'
        replace: '<node_name>wazuh-1</node_name>'
        
    - name: Ejecutar comando sed para cambiar <disabled>yes</disabled> a <disabled>no</disabled> en ossec.conf
      command: "sudo sed -i '/<cluster>/,/<\\/cluster>/ s/<disabled>yes<\\/disabled>/<disabled>no<\\/disabled>/' /var/ossec/etc/ossec.conf"

    - name: Reemplazar node_name
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<key></key>'
        replace: '<key>7d9b3ac77bee4edccc56e64b81dec3ec</key>'
    {% endif %}

    {% if host == 'worker' %}
    - name: Reemplazar node_name
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<key></key>'
        replace: '<key>7d9b3ac77bee4edccc56e64b81dec3ec</key>'

    - name: Reemplazar NODE_IP con la direcci贸n IP
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<node>NODE_IP</node>'
        replace: '<node>192.168.57.2</node>'
        
    - name: Reemplazar NODE_IP con la direcci贸n IP
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<node_name>node01</node_name>'
        replace: '<node_name>wazuh-2</node_name>'

    - name: Ejecutar comando sed para cambiar <disabled>yes</disabled> a <disabled>no</disabled> en ossec.conf
      command: "sudo sed -i '/<cluster>/,/<\\/cluster>/ s/<disabled>yes<\\/disabled>/<disabled>no<\\/disabled>/' /var/ossec/etc/ossec.conf"

    - name: Reemplazar NODE_IP con la direcci贸n IP
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<node_type>master</node_type>'
        replace: '<node_type>worker</node_type>'
    {% endif %}

    - name: Reiniciar Wazuh Manager
      systemd:
        name: wazuh-manager
        state: restarted

    {% if host == 'worker' %}
    - name: Ejecutar cluster_control -l
      command: /var/ossec/bin/cluster_control -l
      register: cluster_output

    - name: Mostrar salida del comando
      debug:
        var: cluster_output.stdout_lines
    {% endif %}