---
- name: Desinstalar y eliminar Wazuh
  hosts: all
  become: yes
  tasks:
    - name: Download install.sh
      get_url:
        url: https://packages.wazuh.com/4.7/wazuh-install.sh
        dest: /home/vagrant/wazuh-install.sh

    - name: Ejecutar comando de desinstalación
      command: "sudo bash wazuh-install.sh --uninstall"
