source 'https://supermarket.chef.io'

metadata

cookbook 'chef-sugar'
cookbook 'hostsfile'
cookbook 'apt'
cookbook 'yum'
cookbook 'poise-python'
cookbook 'wazuh_filebeat', path: "$COOKBOOKS_HOME/wazuh_filebeat/"
cookbook 'wazuh_agent', path: "$COOKBOOKS_HOME/wazuh_agent/"
cookbook 'wazuh_elastic', path: "$COOKBOOKS_HOME/wazuh_elastic/"
