FROM vpgrp/kitchen:latest

ARG source_branch=master

# Update aptitude with new repo
RUN apt-get update

# Clone the corresponding branch of wazuh-puppet
RUN git clone https://github.com/wazuh/wazuh-puppet.git

RUN cd wazuh-puppet && git checkout 3.10.0_7.3.2_bump_version && git branch && git pull

RUN cd wazuh-puppet/kitchen && chmod +x ./run.sh && bundle install

RUN gem uninstall puppet && gem uninstall puppet-module

RUN apt-get -y install ssh && apt-get -y update

RUN cd wazuh-puppet/kitchen && cp test/Dockerfile.template test/Dockerfile

RUN mkdir wazuh-puppet/kitchen/.kitchen

RUN cd wazuh-puppet/kitchen/.kitchen && ssh-keygen -t rsa -N "" -f docker_id_rsa

RUN cd wazuh-puppet/kitchen && sed -i "s|\YOUR_PUBLIC_KEY|$(cat .kitchen/docker_id_rsa.pub)|g" test/Dockerfile

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.5 get-pip.py

RUN pip install pytest && pip install testinfra && pip install paramiko

RUN pip install pytest && pip install testinfra && pip install paramiko

RUN echo "$(sed -n '/ip6/!p' /etc/hosts)" > /etc/hosts