name: Conventional commits
on:
  - pull_request

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Check PR commits
    steps:

    - name: Download files
      uses: actions/checkout@v3

    - name: Install requests dependency
      run: python -m pip install requests

    - name: Run commit names checker script
      run: |
        python .github/workflows/scripts/commits_checker.py -t ${{ secrets.GITHUB_TOKEN }} -p ${{ github.event.number }}
