name: Run script on changed files in sca directory

on:
  pull_request:
    paths:
      - 'sca/**'
jobs:
  Linting:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-20.04
    steps:
      - name: Download files
        uses: actions/checkout@v3

      - name: Install pycodestyle and yamllint linter
        run: python -m pip install pycodestyle==2.8.0 yamllint==1.26.3

      - name: Get the updated files
        id: updated_files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          format: csv

      - name: Save the updated files data
        run: echo ${{ steps.updated_files.outputs.added_modified }}  > updated_files.txt

      - name: Run linter script
        run: |
          chmod +x .github/workflows/scripts/linter.py
          python .github/workflows/scripts/linter.py --file updated_files.txt -c .github/workflows/scripts/config

  Validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6

      - name: Save the updated files data
        run: echo ${{ steps.changed-files.outputs.all_changed_files }} | tr ' ' '\n' | grep ^sca/ > updated_files.txt

      - name: Show changed files
        run: cat updated_files.txt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run script
        run: |
          echo "Running script on ${{ matrix.file }}"
          python .github/workflows/scripts/check_ids.py -f updated_files.txt
